version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  run-test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Check changed files or skip
          command: git show -m HEAD --name-only --pretty="" | egrep -q "^(src|tests|.circleci)|(.js|ts)$" || circleci-agent step halt
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test

workflows:
  my-workflow:
    jobs:
      - run-test