version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  run-test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Check changed files or skip
          command: git show -m HEAD --name-only --pretty="" | egrep -q "^(src|tests|\.circleci).*\.(js|ts|yml)$|^(package\.json|rollup\.config\.js)$" || circleci-agent step halt
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@7
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: npm test

workflows:
  my-workflow:
    jobs:
      - run-test