name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What is the correct/expected behavior?
      placeholder: E.g. button should close the modal
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Describe the incorrect/current behavior?
      placeholder: E.g. button does not close the modal
    validations:
      required: true
  - type: textarea
    id: steps-reproduce
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?
      placeholder: Concise list of steps
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of cookieconsent are you using?
      options:
        - v2.8.0
        - v3.0.0 (Default)
        - other
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/orestbida/cookieconsent/blob/v3.0-beta/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true